// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhUL-XBjRL7iSHXYjHu3A81I_eSmkTIiw',
    appId: '1:218589097975:web:0f6aadeeab8b35936ec8f2',
    messagingSenderId: '218589097975',
    projectId: 'dawat-dhaba-b9241',
    authDomain: 'dawat-dhaba-b9241.firebaseapp.com',
    storageBucket: 'dawat-dhaba-b9241.appspot.com',
    measurementId: 'G-7NSLYCWDCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWZYYtHispljSiVpH-MU4B55tdRW-_Qc',
    appId: '1:218589097975:android:6fd6fbd57d31134f6ec8f2',
    messagingSenderId: '218589097975',
    projectId: 'dawat-dhaba-b9241',
    storageBucket: 'dawat-dhaba-b9241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIfn_5BPTQspxSxTDvCkbPACqgbN0y7Vw',
    appId: '1:218589097975:ios:a0131b8989042e4a6ec8f2',
    messagingSenderId: '218589097975',
    projectId: 'dawat-dhaba-b9241',
    storageBucket: 'dawat-dhaba-b9241.appspot.com',
    iosBundleId: 'com.example.dawatDhaba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIfn_5BPTQspxSxTDvCkbPACqgbN0y7Vw',
    appId: '1:218589097975:ios:a0131b8989042e4a6ec8f2',
    messagingSenderId: '218589097975',
    projectId: 'dawat-dhaba-b9241',
    storageBucket: 'dawat-dhaba-b9241.appspot.com',
    iosBundleId: 'com.example.dawatDhaba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhUL-XBjRL7iSHXYjHu3A81I_eSmkTIiw',
    appId: '1:218589097975:web:5566bff25f019aa96ec8f2',
    messagingSenderId: '218589097975',
    projectId: 'dawat-dhaba-b9241',
    authDomain: 'dawat-dhaba-b9241.firebaseapp.com',
    storageBucket: 'dawat-dhaba-b9241.appspot.com',
    measurementId: 'G-WN967473LL',
  );
}
